python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py
python test/test_sistr_on_3_s_set.py