python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py
python test/test_ours_on_3_s_set.py